#Redisson配置
#singleServerConfig:
#  address: "redis://192.168.1.160:7001"
#  password: null
#  clientName: null
#  database: 7 #选择使用哪个数据库0~15
#  idleConnectionTimeout: 10000
#  pingTimeout: 1000
#  connectTimeout: 10000
#  timeout: 10000
#  retryAttempts: 3
#  retryInterval: 1500
#  reconnectionTimeout: 3000
#  failedAttempts: 3
#  subscriptionsPerConnection: 5
#  subscriptionConnectionMinimumIdleSize: 1
#  subscriptionConnectionPoolSize: 50
#  connectionMinimumIdleSize: 32
#  connectionPoolSize: 64
#  dnsMonitoringInterval: 5000
  #dnsMonitoring: false

#threads: 0
#nettyThreads: 0
#codec:
#  class: "org.redisson.codec.JsonJacksonCodec"
#transportMode: "NIO"

#clusterServersConfig:
#  nodeAddresses:
#    - redis://192.168.1.160:7001
#    - redis://192.168.1.163:7004
#    - redis://192.168.1.165:7006

singleServerConfig:
  # Redis server address
  address: redis://192.168.1.160:7001
  # Minimum idle subscription connection amount
  subscriptionConnectionMinimumIdleSize: 1
  # Redis subscription connection maximum pool size
  subscriptionConnectionPoolSize: 50
  # Minimum idle Redis connection amount
  connectionMinimumIdleSize: 24;
  # Redis connection maximum pool size
  onnectionPoolSize: 64
  # Database index used for Redis connection
  database: 0;
  # Interval in milliseconds to check DNS
  dnsMonitoringInterval: 5000